## Applying Advanced Transformations (Core)
---
* ### Ingrid Arbieto Nelson

### The Data
You will be working with a heavily modified version of the Superheroes dataset from Kaggle.

The dataset includes two csv's:

* superhero_info.csv:
   * Contains Name, Publisher, Demographic Info, and Body measurements.
   
* superhero_powers.csv:
  * Contains Hero name and list of powers
  
### The Task
Your task is two-fold:

#### I. Clean the files and combine them into one final DataFrame.

* This dataframe should have the following columns:
    * Hero (Just the name of the Hero)
    * Publisher
    * Gender
    * Eye color
    * Race
    * Hair color
    * Height (numeric)
    * Skin color
    * Alignment
    * Weight (numeric)
    * Plus, one-hot-encoded columns for every power that appears in the dataset. E.g.:
        * Agility
        * Flight
        * Superspeed
        * etc.

Hint: There is a space in "100 kg" or "52.5 cm"



#### II. Use your combined DataFrame to answer the following questions.

1. Compare the average weight of super powers who have Super Speed to those who do not.
2. What is the average height of heroes for each publisher?


[(Source)](https://www.kaggle.com/datasets/claudiodavi/superhero-set)

Submit your notebook or a link to a GitHub repository with your work.

## I Clean & Combine Dataframe

### Imports

In [1]:
## Standard Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
## Importing the OS and JSON Modules
import os,json

### Load & Clean Files

#### Superhero Info file 
* Hero | Publisher
  * split Hero|Publisher column
* Height & Weight Measurements
  * Separate Measurements into Height & Weight
  * Strip Height & Weight units
  * Convert to numeric

In [2]:
superhero_info = pd.read_csv('Data/superhero_info - superhero_info.csv')
superhero_info.head()

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}"
2,Abin Sur|DC Comics,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}"
3,Abomination|Marvel Comics,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"
4,Absorbing Man|Marvel Comics,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}"

In [3]:
superhero_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Hero|Publisher  463 non-null    object
 1   Gender          463 non-null    object
 2   Race            463 non-null    object
 3   Alignment       463 non-null    object
 4   Hair color      463 non-null    object
 5   Eye color       463 non-null    object
 6   Skin color      463 non-null    object
 7   Measurements    463 non-null    object
dtypes: object(8)
memory usage: 29.1+ KB

In [4]:
## split Hero Publisher into 2 separate columns
superhero_info['Hero|Publisher'].str.split('|',expand=True)

                   0                  1
0             A-Bomb      Marvel Comics
1         Abe Sapien  Dark Horse Comics
2           Abin Sur          DC Comics
3        Abomination      Marvel Comics
4      Absorbing Man      Marvel Comics
..               ...                ...
458     Yellowjacket      Marvel Comics
459  Yellowjacket II      Marvel Comics
460             Yoda       George Lucas
461          Zatanna          DC Comics
462             Zoom          DC Comics

[463 rows x 2 columns]

In [5]:
## save Hero Publisher separated into the dataframe
superhero_info[['Hero','Publisher']] = superhero_info['Hero|Publisher'].str.split('|',expand=True)
superhero_info.head()

,Hero|Publisher,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero,Publisher
0,A-Bomb|Marvel Comics,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics
1,Abe Sapien|Dark Horse Comics,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics
2,Abin Sur|DC Comics,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}",Abin Sur,DC Comics
3,Abomination|Marvel Comics,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",Abomination,Marvel Comics
4,Absorbing Man|Marvel Comics,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}",Absorbing Man,Marvel Comics

In [6]:
## drop the original Hero|Publisher column
superhero_info = superhero_info.drop(columns=['Hero|Publisher'])
superhero_info.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero,Publisher
0,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics
1,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics
2,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}",Abin Sur,DC Comics
3,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",Abomination,Marvel Comics
4,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}",Absorbing Man,Marvel Comics

In [7]:
## examining a single value from the Measurements col
measure = superhero_info.loc[0,"Measurements"]
print(type(measure))
measure

<class 'str'>

"{'Height': '203.0 cm', 'Weight': '441.0 kg'}"

In [8]:
# change ' quote to " quote
measure = measure.replace("'",'"')
measure

'{"Height": "203.0 cm", "Weight": "441.0 kg"}'

In [9]:
## now we can use json.loads
fixed_measure = json.loads(measure)
print(type(fixed_measure))
fixed_measure

<class 'dict'>

{'Height': '203.0 cm', 'Weight': '441.0 kg'}

In [10]:
## use .str.replace to replace all single quotes
superhero_info['Measurements'] = superhero_info['Measurements'].str.replace("'",'"')
## Apply the json.loads to the full column
superhero_info['Measurements'] = superhero_info['Measurements'].apply(json.loads)
superhero_info['Measurements'].head()

0    {'Height': '203.0 cm', 'Weight': '441.0 kg'}
1     {'Height': '191.0 cm', 'Weight': '65.0 kg'}
2     {'Height': '185.0 cm', 'Weight': '90.0 kg'}
3    {'Height': '203.0 cm', 'Weight': '441.0 kg'}
4    {'Height': '193.0 cm', 'Weight': '122.0 kg'}
Name: Measurements, dtype: object

In [11]:
## check a single value after transformation
test_measure = superhero_info.loc[0, 'Measurements']
print(type(test_measure))
test_measure

<class 'dict'>

{'Height': '203.0 cm', 'Weight': '441.0 kg'}

In [12]:
Height_Weight = superhero_info['Measurements'].apply(pd.Series)
Height_Weight

       Height    Weight
0    203.0 cm  441.0 kg
1    191.0 cm   65.0 kg
2    185.0 cm   90.0 kg
3    203.0 cm  441.0 kg
4    193.0 cm  122.0 kg
..        ...       ...
458  183.0 cm   83.0 kg
459  165.0 cm   52.0 kg
460   66.0 cm   17.0 kg
461  170.0 cm   57.0 kg
462  185.0 cm   81.0 kg

[463 rows x 2 columns]

In [13]:
# concat Height_Weight with original dataframe
superhero_info = pd.concat((superhero_info, Height_Weight), axis = 1)
superhero_info.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Measurements,Hero,Publisher,Height,Weight
0,Male,Human,good,No Hair,yellow,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",A-Bomb,Marvel Comics,203.0 cm,441.0 kg
1,Male,Icthyo Sapien,good,No Hair,blue,blue,"{'Height': '191.0 cm', 'Weight': '65.0 kg'}",Abe Sapien,Dark Horse Comics,191.0 cm,65.0 kg
2,Male,Ungaran,good,No Hair,blue,red,"{'Height': '185.0 cm', 'Weight': '90.0 kg'}",Abin Sur,DC Comics,185.0 cm,90.0 kg
3,Male,Human / Radiation,bad,No Hair,green,Unknown,"{'Height': '203.0 cm', 'Weight': '441.0 kg'}",Abomination,Marvel Comics,203.0 cm,441.0 kg
4,Male,Human,bad,No Hair,blue,Unknown,"{'Height': '193.0 cm', 'Weight': '122.0 kg'}",Absorbing Man,Marvel Comics,193.0 cm,122.0 kg

In [14]:
superhero_info = superhero_info.drop(columns=['Measurements'])

In [15]:
superhero_info.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,Height,Weight
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0 cm,441.0 kg
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,191.0 cm,65.0 kg
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,185.0 cm,90.0 kg
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,203.0 cm,441.0 kg
4,Male,Human,bad,No Hair,blue,Unknown,Absorbing Man,Marvel Comics,193.0 cm,122.0 kg

In [16]:
superhero_info['Height'].str.split(' ',expand=True)

         0   1
0    203.0  cm
1    191.0  cm
2    185.0  cm
3    203.0  cm
4    193.0  cm
..     ...  ..
458  183.0  cm
459  165.0  cm
460   66.0  cm
461  170.0  cm
462  185.0  cm

[463 rows x 2 columns]

In [17]:
superhero_info['Weight'].str.split(' ',expand=True)

         0   1
0    441.0  kg
1     65.0  kg
2     90.0  kg
3    441.0  kg
4    122.0  kg
..     ...  ..
458   83.0  kg
459   52.0  kg
460   17.0  kg
461   57.0  kg
462   81.0  kg

[463 rows x 2 columns]

In [18]:
## save split Height & Weight separated into the dataframe
superhero_info[['Height (numeric)','Height_Units']] = superhero_info['Height'].str.split(' ',expand=True)
superhero_info[['Weight (numeric)','Weight_Units']] = superhero_info['Weight'].str.split(' ',expand=True)
superhero_info.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,Height,Weight,Height (numeric),Height_Units,Weight (numeric),Weight_Units
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0 cm,441.0 kg,203.0,cm,441.0,kg
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,191.0 cm,65.0 kg,191.0,cm,65.0,kg
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,185.0 cm,90.0 kg,185.0,cm,90.0,kg
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,203.0 cm,441.0 kg,203.0,cm,441.0,kg
4,Male,Human,bad,No Hair,blue,Unknown,Absorbing Man,Marvel Comics,193.0 cm,122.0 kg,193.0,cm,122.0,kg

In [19]:
## drop the original Height Weight columns
superhero_info = superhero_info.drop(columns=['Height','Weight','Height_Units','Weight_Units'])
superhero_info.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,Height (numeric),Weight (numeric)
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0,441.0
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,191.0,65.0
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,185.0,90.0
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,203.0,441.0
4,Male,Human,bad,No Hair,blue,Unknown,Absorbing Man,Marvel Comics,193.0,122.0

In [20]:
superhero_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Gender            463 non-null    object
 1   Race              463 non-null    object
 2   Alignment         463 non-null    object
 3   Hair color        463 non-null    object
 4   Eye color         463 non-null    object
 5   Skin color        463 non-null    object
 6   Hero              463 non-null    object
 7   Publisher         463 non-null    object
 8   Height (numeric)  463 non-null    object
 9   Weight (numeric)  463 non-null    object
dtypes: object(10)
memory usage: 36.3+ KB

In [21]:
superhero_info['Height (numeric)'] = superhero_info['Height (numeric)'].astype("float")

In [22]:
superhero_info['Weight (numeric)'] = superhero_info['Weight (numeric)'].astype("float")

In [23]:
superhero_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 463 entries, 0 to 462
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Gender            463 non-null    object
 1   Race              463 non-null    object
 2   Alignment         463 non-null    object
 3   Hair color        463 non-null    object
 4   Eye color         463 non-null    object
 5   Skin color        463 non-null    object
 6   Hero              463 non-null    object
 7   Publisher         463 non-null    object
 8   Height (numeric)  463 non-null    float64
 9   Weight (numeric)  463 non-null    float64
dtypes: float64(2), object(8)
memory usage: 36.3+ KB

#### Superhero Powers file

In [24]:
superhero_powers = pd.read_csv('Data/superhero_powers - superhero_powers.csv')
superhero_powers.head()

    hero_names                                             Powers
0      3-D Man         Agility,Super Strength,Stamina,Super Speed
1       A-Bomb  Accelerated Healing,Durability,Longevity,Super...
2   Abe Sapien  Agility,Accelerated Healing,Cold Resistance,Du...
3     Abin Sur                                 Lantern Power Ring
4  Abomination  Accelerated Healing,Intelligence,Super Strengt...

In [25]:
superhero_powers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 667 entries, 0 to 666
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   hero_names  667 non-null    object
 1   Powers      667 non-null    object
dtypes: object(2)
memory usage: 10.5+ KB

In [26]:
## saving the unique values from the exploded column
cols_to_make = superhero_powers['Powers'].str.split(',', expand=True).dropna()
cols_to_make

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
563,Agility,Accelerated Healing,Dimensional Awareness,Stealth,Energy Absorption,Flight,Marksmanship,Longevity,Intelligence,Super Strength,...,Levitation,Time Travel,Illusions,Water Control,Omnilingualism,Time Manipulation,Invisibility,Sub-Mariner,Vision - Heat,Reality Warping

In [27]:
#for col in cols_to_make:
#    superhero_powers['col'] = superhero_powers['Powers'].str.contains('col')
superhero_powers.head()

    hero_names                                             Powers
0      3-D Man         Agility,Super Strength,Stamina,Super Speed
1       A-Bomb  Accelerated Healing,Durability,Longevity,Super...
2   Abe Sapien  Agility,Accelerated Healing,Cold Resistance,Du...
3     Abin Sur                                 Lantern Power Ring
4  Abomination  Accelerated Healing,Intelligence,Super Strengt...

### Merge files

In [28]:
## example merge with our 2 dataframes
superheroes = pd.merge(superhero_info, superhero_powers, left_on='Hero', right_on='hero_names', how='inner')
superheroes.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,Height (numeric),Weight (numeric),hero_names,Powers
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0,441.0,A-Bomb,"Accelerated Healing,Durability,Longevity,Super..."
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,191.0,65.0,Abe Sapien,"Agility,Accelerated Healing,Cold Resistance,Du..."
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,185.0,90.0,Abin Sur,Lantern Power Ring
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,203.0,441.0,Abomination,"Accelerated Healing,Intelligence,Super Strengt..."
4,Male,Human,bad,No Hair,blue,Unknown,Absorbing Man,Marvel Comics,193.0,122.0,Absorbing Man,"Cold Resistance,Durability,Energy Absorption,S..."

In [29]:
superheroes = superheroes.drop(columns=['hero_names'])
superheroes.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,Height (numeric),Weight (numeric),Powers
0,Male,Human,good,No Hair,yellow,Unknown,A-Bomb,Marvel Comics,203.0,441.0,"Accelerated Healing,Durability,Longevity,Super..."
1,Male,Icthyo Sapien,good,No Hair,blue,blue,Abe Sapien,Dark Horse Comics,191.0,65.0,"Agility,Accelerated Healing,Cold Resistance,Du..."
2,Male,Ungaran,good,No Hair,blue,red,Abin Sur,DC Comics,185.0,90.0,Lantern Power Ring
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,203.0,441.0,"Accelerated Healing,Intelligence,Super Strengt..."
4,Male,Human,bad,No Hair,blue,Unknown,Absorbing Man,Marvel Comics,193.0,122.0,"Cold Resistance,Durability,Energy Absorption,S..."

## II. SuperHero Questions

### Compare the average weight of super powers who have Super Speed to those who do not.

* #### The average weight of SuperHeroes with the SuperPower of "Super Speed" is 129.40 kg.
* ####  The average weight of SuperHeroes without "Super Speed" is 101.77 kg.
* #### SuperHeroes with "Super Speed on average weigh more!

In [30]:
# create filter for superheroes with super speed
SuperSpeed_filter = superheroes['Powers'].str.contains('Super Speed') == True

In [31]:
# find df for superheroes with super speed
superspeed_df = superheroes.loc[SuperSpeed_filter,:]

In [36]:
# top 5 rows for superheroes with super speed
superspeed_df.head()

,Gender,Race,Alignment,Hair color,Eye color,Skin color,Hero,Publisher,Height (numeric),Weight (numeric),Powers
3,Male,Human / Radiation,bad,No Hair,green,Unknown,Abomination,Marvel Comics,203.0,441.0,"Accelerated Healing,Intelligence,Super Strengt..."
5,Male,Human,good,Blond,blue,Unknown,Adam Strange,DC Comics,185.0,88.0,"Durability,Stealth,Flight,Marksmanship,Weapons..."
8,Male,Unknown,bad,White,blue,Unknown,Air-Walker,Marvel Comics,188.0,108.0,"Flight,Super Strength,Super Speed,Self-Sustena..."
9,Male,Cyborg,bad,Black,brown,Unknown,Ajax,Marvel Comics,193.0,90.0,"Agility,Super Strength,Super Speed,Heat Genera..."
10,Male,Unknown,good,Blond,blue,Unknown,Alan Scott,DC Comics,180.0,90.0,"Flight,Danger Sense,Intelligence,Telepathy,Ene..."

In [33]:
# create df for superheroes WITHOUT super speed
no_superspeed_df = superheroes.loc[~SuperSpeed_filter,:]

In [34]:
# find average weight for superheroes with super speed
superspeed_df['Weight (numeric)'].mean()

129.40404040404042

In [35]:
# find average weight for superheroes WITHOUT super speed
no_superspeed_df['Weight (numeric)'].mean()

101.77358490566037

### What is the average height of heroes for each publisher?

In [37]:
# use groupby function to find average height by publisher
superheroes.groupby('Publisher')['Height (numeric)'].mean()

Publisher
DC Comics            181.923913
Dark Horse Comics    176.909091
George Lucas         159.600000
Image Comics         211.000000
Marvel Comics        191.546128
Shueisha             171.500000
Star Trek            181.500000
Team Epic TV         180.750000
Unknown              178.000000
Name: Height (numeric), dtype: float64